server:
  port: 8083

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/order/**
          filters: 
            - StripPrefix=3
            - JwtValidation
    
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/product/**
          filters:
            - StripPrefix=3
            - JwtValidation
      

        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3

grpc:
  client:
    auth-service:
      address: 'static://localhost:9010'
      negotiationType: PLAINTEXT
      enableKeepAlive: true
      keepAliveWithoutCalls: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    com.example.api_gateway: DEBUG  
    net.devh.boot.grpc: DEBUG


